Add Huawei Bisheng to JDKs.
sdkman/sdkman-candidates pull request #67
Opened 2023-11-14 08:23 UTC by tonycody

Bisheng JDK is the open source version of Huawei JDK, which is customized based on OpenJDK. Huawei JDK runs on more than 500 Huawei products, and the R&D team has accumulated rich development experience and solved a number of difficult problems encountered in the actual operation of the business.
Bisheng JDK, as the downstream of OpenJDK, is a high-performance OpenJDK distribution that can be used in production environments. Bisheng JDK fixes some performance and stability problems encountered in Huawei's internal application scenarios, and makes performance optimization and stability enhancement on ARM architecture, which is more stable on ARM architecture and can get better performance in big data and other scenarios.
Bisheng JDK is dedicated to provide JAVA developers with a stable, reliable, high-performance and easy-to-tune JDK, as well as a better choice for users on ARM architecture.
Currently there are 3 major versions, [8](https://gitee.com/openeuler/bishengjdk-8), [11](https://gitee.com/openeuler/bishengjdk-11) and [17](https://gitee.com/openeuler/bishengjdk-17).

2023-11-16 09:43 UTC, tonycody commented
pong

2023-12-05 10:36 UTC, marc0der approved these changes

2023-12-05 10:37 UTC, marc0der requested changes
Seems like we have failing tests. Can you look into this @tonycody?

2023-12-05 10:40 UTC, tonycody commented
> Seems like we have failing tests. Can you look into this @tonycody?

ok

2023-12-05 10:49 UTC, tonycody commented
![image](https://github.com/sdkman/sdkman-candidates/assets/6773121/d9bf8e6f-2c9d-481e-b089-af798f1fc28f)
@marc0der 
I don't understand why this failed, what do I need to do?
Can you tell me what I need to do?

2023-12-05 10:51 UTC, tonycody commented
@marc0der Are you slack online?

2023-12-05 11:55 UTC, tonycody commented
@marc0der Hello, please help to approve it again

2023-12-18 23:05 UTC, marc0der commented
I've merged this PR from the CLI, but GitHub is not recognising it. Closing this here now.

2023-12-18 23:05 UTC, closed without merging

2023-12-21 02:03 UTC, tonycody commented
@marc0der @eddumelendez https://github.com/sdkman/sdkman-disco-integration/pull/17
This PR help review it, right?